### ISSUE TITLE
Text appears wrong in preview from template screen

### ISSUE THREAD

**Issue by kieranoreilly** [expandorg/requester-app#67]
https://www.useloom.com/share/250ecaafba9f4cf3811bd7026f58a253

**Comment by danton721** [comment]
> fixed - i implemented simple regex which will wrap all not wrapped content into `<p>`

@sslava do you mind sharing RegEx? Thanks!

**Comment by sslava** [comment]
Hey @danton721!  Sure, it was something like:
```js
  text.replace(/([^>]*)(?![^<]*>|[^<>]*<\/)/g, full =>
    !full || full === ' ' ? full : `<p>${full}</p>`
  );
```
It doesn't work well for all the cases but at least fixes some.
